site_name: Arizona Meshtastic Community
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

site_url: https://azmsh.net
repo_name: azmsh-site
repo_url: https://github.com/ArizonaMeshtasticCommunity/azmsh-site

nav:
  - Home: index.md
  - How to Connect: docs/how-to-connect.md
  - What Now?: docs/what-now.md
  - Recommended Hardware: docs/recommended-hardware.md
  - Recommended Settings: docs/recommended-settings.md
  - Suggested Channels: docs/suggested_channels.md
  - Host a Node: docs/host-a-node.md
  - Reach Out: reach_out.md

plugins:
  - offline
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/extra.css # Discord-gated settings boxes

extra_javascript:
  - assets/js/nodeData.js # Node Info

copyright: Copyright &copy; 2025 Arizona Meshtastic Community
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HrKtyuFEQk
    - icon: fontawesome/brands/github
      link: https://github.com/ArizonaMeshtasticCommunity
